exclude: ^venv
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-json
      - id: check-symlinks
      - id: check-merge-conflict
      - id: name-tests-test
        args: ['--django']
        exclude: '(const.py|Helpers)'
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
        exclude: 'static'
      - id: fix-encoding-pragma
        args: ['--remove']
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: sort-simple-yaml
  -   repo: https://github.com/asottile/pyupgrade
      rev: v2.31.0
      hooks:
      -   id: pyupgrade
          args: ['--py38-plus']
  -   repo: https://github.com/psf/black
      rev: 21.12b0
      hooks:
      -   id: black
  -   repo: https://github.com/asottile/add-trailing-comma
      rev: v2.2.1
      hooks:
      -   id: add-trailing-comma
  -   repo: https://gitlab.com/pycqa/flake8
      rev: 3.9.2
      hooks:
      - id: flake8
        additional_dependencies: [
          flake8-2020,
          flake8-bugbear,
          flake8-comprehensions,
          flake8-debugger,
          flake8-docstrings,
          yesqa,
          wemake_python_styleguide]
  -   repo: https://github.com/pre-commit/mirrors-isort
      rev: v5.10.1
      hooks:
        - id: isort
          args: ["--settings-file", "pyproject.toml"]
  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-check-blanket-noqa
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
